install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe'
  - rustup-init.exe -y --profile minimal
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

build_script:
  - cargo build

test_script:
  - cargo test

cache:
  - '%USERPROFILE%\.cargo'
  - target
