language: rust

rust:
  - 1.8.0
  - stable
  - beta
  - nightly

cache: cargo

before_install:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "1.8.0" ]]; then
          echo "Old Rust detected, removing version-sync dependency"
          sed -i "/^version-sync =/d" Cargo.toml
          rm "tests/version-numbers.rs"
      fi

matrix:
  allow_failures:
    - rust: nightly
